version: '3.7'
services:
  router:
    image: traefik:latest
    container_name: router
    ports:
      - 80:80
      - 443:443 
    restart: always
    depends_on:
      - watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik-acme:/acme
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.web.acme.email=example@example.com"
      - "--certificatesresolvers.web.acme.storage=/acme/certs.json"
      - "--certificatesresolvers.web.acme.httpchallenge.entrypoint=web"
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.scope=nosh"
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    restart: always
    depends_on:
      - router
      - watchtower
    env_file:
      - ./.env
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    volumes:
      - ./dbdata:/opt/couchdb/data
      - ./dbconfig:/opt/couchdb/etc/local.d
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.services.couchdb.loadbalancer.server.port=5984"
      - "traefik.http.routers.couchdb.entrypoints=web"
      - "traefik.http.routers.couchdb.rule=Host(`db.example.com`)"
      - "traefik.http.middlewares.couchdb-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.couchdb.middlewares=couchdb-https-redirect"
      - "traefik.http.routers.couchdb-secure.entrypoints=websecure"
      - "traefik.http.routers.couchdb-secure.rule=Host(`db.example.com`)"
      - "traefik.http.routers.couchdb-secure.tls=true"
      - "traefik.http.routers.couchdb-secure.tls.certresolver=web"
      - "traefik.http.routers.couchdb-secure.service=couchdb"
      - "com.centurylinklabs.watchtower.scope=nosh"
  nosh:
    image: shihjay2/nosh3 
    container_name: nosh 
    links:
      - couchdb
    restart: always
    depends_on:
      - couchdb
      - router
      - watchtower
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.services.nosh.loadbalancer.server.port=4000"
      - "traefik.http.routers.nosh.entrypoints=web"
      - "traefik.http.routers.nosh.rule=Host(`example.com`)"
      - "traefik.http.middlewares.nosh-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nosh.middlewares=nosh-https-redirect"
      - "traefik.http.routers.nosh-secure.entrypoints=websecure"
      - "traefik.http.routers.nosh-secure.rule=Host(`example.com`)"
      - "traefik.http.routers.nosh-secure.tls=true"
      - "traefik.http.routers.nosh-secure.tls.certresolver=web"
      - "traefik.http.routers.nosh-secure.service=nosh"
      - "com.centurylinklabs.watchtower.scope=nosh"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope nosh --cleanup
    labels:
      - "traefik.enable=false"
networks:
  traefik_default:
    external: true